// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Item struct {
	ID           int32
	Brand        string
	Model        string
	Description  sql.NullString
	SerialNumber string
	CreatedAt    sql.NullTime
}
