// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Analyzer struct {
	AnalyzerID              int32
	ItemID                  sql.NullInt32
	AnalyzerState           interface{}
	AnalyzerPollutant       interface{}
	AnalyzerLastCalibration sql.NullTime
	AnaluzerLastMaintenance sql.NullTime
}

type Cylinder struct {
	CylinderID             int32
	ItemID                 sql.NullInt32
	CylinderGas            interface{}
	CylinderSize           interface{}
	CyliinderUnit          interface{}
	CylinderConcentration  sql.NullString
	CylinderExpirationDate sql.NullTime
}

type Inventory struct {
	ItemID    int32
	StationID int32
	Quantity  int32
}

type Item struct {
	ItemID           int32
	ItemBrand        string
	ItemModel        string
	ItemDescription  string
	ItemSerialNumber string
	ItemImageUrl     sql.NullString
	ItemSupplier     sql.NullString
	CreatedAt        sql.NullTime
}

type ItemsPart struct {
	ItemID int32
	PartID int32
}

type Part struct {
	PartID    int32
	ItemID    sql.NullInt32
	PartState interface{}
}

type Station struct {
	StationID          int32
	StationName        string
	StationImageUrl    sql.NullString
	StationDescription sql.NullString
	OperationalSince   sql.NullTime
}
