// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: item_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    item_type_id,
    item_name,
    item_description
)
VALUES (
    $1,
    $2,
    $3
) RETURNING item_id
`

type CreateItemParams struct {
	ItemTypeID      int32       `json:"item_type_id"`
	ItemName        string      `json:"item_name"`
	ItemDescription pgtype.Text `json:"item_description"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, createItem, arg.ItemTypeID, arg.ItemName, arg.ItemDescription)
	var item_id int32
	err := row.Scan(&item_id)
	return item_id, err
}

const getItems = `-- name: GetItems :many
SELECT
    i.item_id,
    i.item_name,
    i.item_description,
    i.created_at,
    it.type_name AS item_type
FROM
    items i
JOIN
    item_types it ON i.item_type_id = it.item_type_id
`

type GetItemsRow struct {
	ItemID          int32              `json:"item_id"`
	ItemName        string             `json:"item_name"`
	ItemDescription pgtype.Text        `json:"item_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ItemType        string             `json:"item_type"`
}

func (q *Queries) GetItems(ctx context.Context) ([]GetItemsRow, error) {
	rows, err := q.db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsRow
	for rows.Next() {
		var i GetItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.ItemDescription,
			&i.CreatedAt,
			&i.ItemType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStations = `-- name: GetStations :many
SELECT station_id, station_name, station_image_url, operational_since, station_latitude, station_longitude, station_address
FROM stations
`

type GetStationsRow struct {
	StationID        int32          `json:"station_id"`
	StationName      string         `json:"station_name"`
	StationImageUrl  pgtype.Text    `json:"station_image_url"`
	OperationalSince pgtype.Date    `json:"operational_since"`
	StationLatitude  pgtype.Numeric `json:"station_latitude"`
	StationLongitude pgtype.Numeric `json:"station_longitude"`
	StationAddress   pgtype.Text    `json:"station_address"`
}

func (q *Queries) GetStations(ctx context.Context) ([]GetStationsRow, error) {
	rows, err := q.db.Query(ctx, getStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStationsRow
	for rows.Next() {
		var i GetStationsRow
		if err := rows.Scan(
			&i.StationID,
			&i.StationName,
			&i.StationImageUrl,
			&i.OperationalSince,
			&i.StationLatitude,
			&i.StationLongitude,
			&i.StationAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
