// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analyzer struct {
	AnalyzerID              int32
	ItemID                  pgtype.Int4
	AnalyzerState           interface{}
	AnalyzerPollutant       interface{}
	AnalyzerLastCalibration pgtype.Date
	AnaluzerLastMaintenance pgtype.Date
}

type Cylinder struct {
	CylinderID             int32
	ItemID                 pgtype.Int4
	CylinderGas            interface{}
	CylinderSize           interface{}
	CyliinderUnit          interface{}
	CylinderConcentration  pgtype.Numeric
	CylinderExpirationDate pgtype.Date
}

type Inventory struct {
	ItemID    int32
	StationID int32
	Quantity  int32
}

type Item struct {
	ItemID           int32
	ItemBrand        string
	ItemModel        string
	ItemDescription  string
	ItemSerialNumber string
	ItemImageUrl     pgtype.Text
	ItemSupplier     pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type ItemsPart struct {
	ItemID int32
	PartID int32
}

type Part struct {
	PartID    int32
	ItemID    pgtype.Int4
	PartState interface{}
}

type Station struct {
	StationID          int32
	StationName        string
	StationImageUrl    pgtype.Text
	StationDescription pgtype.Text
	OperationalSince   pgtype.Date
}
