// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analyzer struct {
	AnalyzerID              int32       `json:"analyzer_id"`
	ItemID                  int32       `json:"item_id"`
	AnalyzerStateID         int32       `json:"analyzer_state_id"`
	AnalyzerPollutantID     int32       `json:"analyzer_pollutant_id"`
	AnalyzerLastCalibration pgtype.Date `json:"analyzer_last_calibration"`
	AnalyzerLastMaintenance pgtype.Date `json:"analyzer_last_maintenance"`
}

type Brand struct {
	BrandID   int32  `json:"brand_id"`
	BrandName string `json:"brand_name"`
}

type ConcentrationUnit struct {
	ConcentrationUnitID int32  `json:"concentration_unit_id"`
	UnitName            string `json:"unit_name"`
}

type Cylinder struct {
	CylinderID             int32          `json:"cylinder_id"`
	ItemID                 int32          `json:"item_id"`
	CylinderGasTypeID      int32          `json:"cylinder_gas_type_id"`
	CylinderSizeID         int32          `json:"cylinder_size_id"`
	CylinderUnitID         int32          `json:"cylinder_unit_id"`
	CylinderConcentration  pgtype.Numeric `json:"cylinder_concentration"`
	CylinderExpirationDate pgtype.Date    `json:"cylinder_expiration_date"`
}

type CylinderSize struct {
	CylinderSizeID int32  `json:"cylinder_size_id"`
	SizeName       string `json:"size_name"`
}

type GasType struct {
	GasTypeID   int32  `json:"gas_type_id"`
	GasTypeName string `json:"gas_type_name"`
}

type Inventory struct {
	ItemID     int32              `json:"item_id"`
	StationID  int32              `json:"station_id"`
	Quantity   int32              `json:"quantity"`
	LastUpdate pgtype.Timestamptz `json:"last_update"`
	UpdatedBy  string             `json:"updated_by"`
}

type Item struct {
	ItemID           int32              `json:"item_id"`
	ModelID          int32              `json:"model_id"`
	ItemDescription  string             `json:"item_description"`
	ItemSerialNumber string             `json:"item_serial_number"`
	ItemImageUrl     pgtype.Text        `json:"item_image_url"`
	ItemSupplier     pgtype.Text        `json:"item_supplier"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ItemState struct {
	ItemStateID int32  `json:"item_state_id"`
	StateName   string `json:"state_name"`
}

type ItemsPart struct {
	ItemID int32 `json:"item_id"`
	PartID int32 `json:"part_id"`
}

type Model struct {
	ModelID   int32  `json:"model_id"`
	BrandID   int32  `json:"brand_id"`
	ModelName string `json:"model_name"`
}

type Part struct {
	PartID      int32 `json:"part_id"`
	ItemID      int32 `json:"item_id"`
	PartStateID int32 `json:"part_state_id"`
}

type PartState struct {
	PartStateID   int32  `json:"part_state_id"`
	PartStateName string `json:"part_state_name"`
}

type Pollutant struct {
	PollutantID   int32  `json:"pollutant_id"`
	PollutantName string `json:"pollutant_name"`
}

type Station struct {
	StationID          int32          `json:"station_id"`
	StationName        string         `json:"station_name"`
	StationImageUrl    pgtype.Text    `json:"station_image_url"`
	StationLatitude    pgtype.Numeric `json:"station_latitude"`
	StationLongitude   pgtype.Numeric `json:"station_longitude"`
	StationAddress     pgtype.Text    `json:"station_address"`
	StationDescription pgtype.Text    `json:"station_description"`
	OperationalSince   pgtype.Date    `json:"operational_since"`
}

type Traslado struct {
	TrasladoID       int32              `json:"traslado_id"`
	ItemID           int32              `json:"item_id"`
	StationIDOrigen  int32              `json:"station_id_origen"`
	StationIDDestino int32              `json:"station_id_destino"`
	Cantidad         int32              `json:"cantidad"`
	FechaTraslado    pgtype.Timestamptz `json:"fecha_traslado"`
}
